name: dotnet package

on:
  push:
    paths-ignore:
      - 'UI/**'
      
env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry
  
jobs:
  build:

    runs-on: windows-2022
    strategy:
      matrix:
        dotnet-version: ['7.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
      - name: Install dependencies Core.Test
        run: dotnet restore Core.Test/Core.Test.csproj
      - name: Install dependencies UI
        run: dotnet restore UI/UI.csproj
      - name: Install dependencies EF.Test
        run: dotnet restore EF.Test/EF.Test.csproj
      - name: Install dependencies Services.Test
        run: dotnet restore Services.Test/Services.Test.csproj
      - name: Build Core.Test
        run: dotnet build Core.Test/Core.Test.csproj --configuration Release --no-restore
      - name: Build EF.Test
        run: dotnet build EF.Test/EF.Test.csproj --configuration Release --no-restore
      - name: Build Services.Test
        run: dotnet build Services.Test/Services.Test.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
